deployment:
  replicas: 2
  imageVersion: v1
  imageURL: 315069654700.dkr.ecr.us-east-1.amazonaws.com/expense/dev/frontend
hpa:
  cpuUtilization: 15
tgb:
  arn: arn:aws:elasticloadbalancing:us-east-1:315069654700:targetgroup/expense-dev/13fe6e903e7ead3e